<?xml version="1.0" encoding="UTF-8"?><testrun name="TestCases" project="AdvanceProgramming" tests="26" started="26" failures="9" errors="0" ignored="0">
  <testsuite name="TestCases" time="0.068">
    <testcase name="testUser_WithdrawAmount_Test_1" classname="TestCases" time="0.015">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testUser_WithdrawAmount_Test_1(TestCases.java:103)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUser_WithdrawAmount_Test_2" classname="TestCases" time="0.001"/>
    <testcase name="testUser_WithdrawAmount_Test_3" classname="TestCases" time="0.0"/>
    <testcase name="testUser_WithdrawAmount_Test_4" classname="TestCases" time="0.001"/>
    <testcase name="testUser_WithdrawAmount_Test_5" classname="TestCases" time="0.001"/>
    <testcase name="testUser_DepositeAmount_Test_1" classname="TestCases" time="0.0">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testUser_DepositeAmount_Test_1(TestCases.java:93)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUser_DepositeAmount_Test_2" classname="TestCases" time="0.0"/>
    <testcase name="testAdmin_CreateAccount_Test_2" classname="TestCases" time="0.002">
      <failure>junit.framework.AssertionFailedError: expected:&lt;false&gt; but was:&lt;true&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testAdmin_CreateAccount_Test_2(TestCases.java:18)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testAdmin_CalculateInterest_Test_1" classname="TestCases" time="0.015"/>
    <testcase name="testAdmin_CalculateInterest_Test_2" classname="TestCases" time="0.0"/>
    <testcase name="testAdmin_PrintStatement_Test_1" classname="TestCases" time="0.007"/>
    <testcase name="testAdmin_PrintStatement_Test_2" classname="TestCases" time="0.001"/>
    <testcase name="testAdmin_DeleteAccount_Test_2" classname="TestCases" time="0.005"/>
    <testcase name="testAdmin_DeleteAccount_Test_3" classname="TestCases" time="0.002"/>
    <testcase name="testAdmin_DeleteAccount_Test_4" classname="TestCases" time="0.004">
      <failure>junit.framework.AssertionFailedError: expected:&lt;false&gt; but was:&lt;true&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testAdmin_DeleteAccount_Test_4(TestCases.java:88)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testAdmin_PrintDeduction_Test_1" classname="TestCases" time="0.004">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testAdmin_PrintDeduction_Test_1(TestCases.java:48)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testAdmin_PrintDeduction_Test_2" classname="TestCases" time="0.001"/>
    <testcase name="testAdmin_PrintDeduction_Test_3" classname="TestCases" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testAdmin_PrintDeduction_Test_3(TestCases.java:58)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUser_TransferAmount_Test_1" classname="TestCases" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testUser_TransferAmount_Test_1(TestCases.java:138)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUser_TransferAmount_Test_2" classname="TestCases" time="0.0"/>
    <testcase name="testUser_TransferAmount_Test_3" classname="TestCases" time="0.001"/>
    <testcase name="testUser_TransferAmount_Test_4" classname="TestCases" time="0.0"/>
    <testcase name="testUser_CheckAmount_Test_1" classname="TestCases" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testUser_CheckAmount_Test_1(TestCases.java:128)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testUser_CheckAmount_Test_2" classname="TestCases" time="0.001"/>
    <testcase name="testAdmin_CheckZakat_Test_1" classname="TestCases" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:174)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:181)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:324)&#13;
	at TestCases.testAdmin_CheckZakat_Test_1(TestCases.java:25)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testAdmin_CheckZakat_Test_2" classname="TestCases" time="0.0"/>
  </testsuite>
</testrun>
